### ISSUE TITLE
Document random seeds, and allow specification of seeds for reproducibility and testing

### ISSUE THREAD

**Issue by nealmcb** [electology/vse-sim#13]
The ability to replicate results is critical for simulations and other scientific results used in policy discussions related to fundamental aspects of society like election methods.

For replication of results, testing and exploring the implications of election simulations, the system needs to document the random seeds used in each simulation when reporting the results, and allow the user to specify the seed for a simulation and any other parameters necessary to reproduce the result.

For background on reproducability in another complicated and important field, see [A minimum standard for publishing computational results in the weather and climate sciences:  Damien Irving](http://journals.ametsoc.org/doi/abs/10.1175/BAMS-D-15-00010.1)

**Comment by jamesonquinn** [comment]
closed with commit ed381fd76d31cd92d7a72dd3bc015ddf1a6863f9 (save seed; resolves #13)
